### ISSUE TITLE
The following characters don't get displayed when typed -=\/|:;<>,?`[]{}

### ISSUE THREAD

**Issue by heathgr** [enquirer/prompt-base#5]
-=\/|:;<>,?`[]{} None of the preceding characters get displayed on the prompt when typed.  They will display if another character is typed after they are typed.  The correct value does get returned by the run function, even if it doesn't get displayed correctly when it's typed.

This is just a guess, but this is probably related to #4.

**Comment by jonschlinkert** [comment]
Hmm, I'm guessing this is because the keypress lib we use doesn't emit for those. Seems like all of those characters should work though. we'll look into it, a PR would also be great.

thanks for the issue.

**Comment by jonschlinkert** [comment]
Currently, for some special characters like `#` the keypress event name is the actual symbol, not a semantic name like `hash` or `pound`. Seems like the names should be semantic though. Any thoughts or opinions on this before I update?

@doowb / @heathgr?

**Comment by jonschlinkert** [comment]
k, here are the names I'm planning to use (fwiw, in cases where characters have more than one name to choose from, like `asterisk` vs `star`, I've chosen to use the shorter, more user-friendly names)

edit: nvm, the more I think about this, the more I think we should just emit the characters, like we do with alphabetical chars. That way you'll never have to consult the docs to see which semantic name to use. just use the character. 

| **Character** | **event.key.name** |
| --- | --- |
| `[` | ltbracket |
| `]` | rtbracket |
| `(` | ltparen |
| `)` | rtparen |
| `<` | ltangle |
| `>` | rtangle |
| `{` | ltbrace |
| `}` | rtbrace |
| `!` | bang |
| `#` | hash |
| `$` | dollar |
| `%` | percent |
| `&` | ampersand |
| `*` | star |
| `+` | plus |
| `,` | comma |
| `.` | dot |
| `/` | slash |
| `:` | colon |
| `;` | semicolon |
| `=` | equal |
| `?` | qmark |
| `@` | at |
| `\` | backslash |
| `^` | carat |
| `_` | underscore |
| <code>`</code> | backtick |
| `|` | bar |
| `~` | tilde |
| `–` | dash |
| `'` | apostrophe |
| `"` | quote |

**Comment by doowb** [comment]
These look good to me. We should export a couple of maps to make it easier on implementors to handle symbols if necessary.

```js
prompt.on(utils.charmap.CARAT, console.log);
```

Even though the values will be the same (just lowercase) as the keys, some editors have good IntelliSense that helps and we can add keys for the alternative names. This will also be good if we need to make a change to the underlying value, but keep the key the same.

**Comment by jonschlinkert** [comment]
lol sorry I just updated my comment. You're hitting on what I mention

**Comment by doowb** [comment]
Yeah, I was thinking the same type of thing because we are already emitting them in `readline-ui` if the "event" comes back with a name.

**Comment by jonschlinkert** [comment]
how about if we do semantic names for some of them? specifically, ones that do not have (common) alternate names. Like `backslash` and `slash` (yes, I know you can call a backslash a `backslant` or a `backwhack`, but who does that? lol)

wow I'm never this indecisive lol. must be something about these symbols that has me mesmerized. 

edit: hmm, I forgot that the `event.value` has the original character. so maybe using the semantic names for all/most of them is okay.
