### ISSUE TITLE
Customize prefix in constructor

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-base#7]
instead of only as an instance property, example: https://github.com/enquirer/prompt-base/blob/master/examples/ask.prefix.js#L8

**Comment by jonschlinkert** [comment]
It should work when passed to the ctor, if it doesn't that's a bug.

**Comment by stevenvachon** [comment]
Then we have a bug:

```js
const confirm = new Confirm({
	message: `Delete "${name}" database and "${user}" user?`,
	default: false,
	prefix: ""
});

// doesn't remove "?"
```

**Comment by jonschlinkert** [comment]
noted, marking as a bug. thank you

**Comment by stevenvachon** [comment]
For now, I'm using `\ufeff` (zero-width non-breaking space) as a value, since `''` must be failing a truthy condition.

**Comment by jonschlinkert** [comment]
I believe this was fixed by https://github.com/enquirer/prompt-base/pull/10
