### ISSUE TITLE
Option to remove on exit

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-base#8]
I'm using [prompt-confirm](https://npmjs.com/prompt-confirm) for a single "Are you sure? (y/N)" confirmation in a delete operation. There is no point in me keeping this in stdout. It'd be great if there was a way to have it auto-removed on exit.

**Comment by jonschlinkert** [comment]
I need to double check but I think this is handled by `prompt.end()`

**Comment by jonschlinkert** [comment]
Did you try calling `prompt.end()`?

**Comment by stevenvachon** [comment]
Yes, it just adds a second instance of the prompt text.

**Comment by doowb** [comment]
@stevenvachon I just want to clarify what you're asking for. After the user submits an answer to the prompt, you want the line cleared so the question and answer are not shown on stdout.

If this is the case then you can override the `message` using an on `render` event listener:

```js
prompt.on('render', function(context) {
  if (context.status === 'answered') {
    context.message = '';
    // this might not be needed since it should be empty here already
    context.append = '';
  }
});
```

We're still working on this API and the structure of the `context` object, but it shouldn't change much from what it is now.

**Comment by stevenvachon** [comment]
Thank you, that sort of worked. The line was emptied, but not cleared.

There're definitely inconsistencies in the API for customizing the display: `renderMessage()`, `on('render')`.

**Comment by doowb** [comment]
`on('render')` is just the event that's fired each time the prompt needs to be rendered (like with each keypress, when an answer is submitted, and when the final answer is going to be rendered). This provides the option to override properties on the `context` just before the prompt is rendered to the stdout.

There's also a [.renderAnswer](https://github.com/enquirer/prompt-base#renderanswer) method that can be overridden to just return `''`. This is the method that's called when `context.status === 'answered'` and the return value is set to `context.message` (which is the value passed to stdout).

> The line was emptied, but not cleared.

I'm not exactly sure what you mean here. Are you able to show screenshots or something that show exactly what's happening?

**Comment by stevenvachon** [comment]
before:
![before](https://user-images.githubusercontent.com/170197/28075308-18e51bdc-6629-11e7-8686-50b8702a863f.png)

after:
![after](https://user-images.githubusercontent.com/170197/28075310-1bbbbed8-6629-11e7-9086-66b08acab7f5.png)

**Comment by jonschlinkert** [comment]
Oh I see. So basically instead of just clearing the line (so that it's an empty string), we need to back up a line in the terminal. 

you should be able to do this using ansi escapes:

```js
// move up a line 
process.stdout.write('\u001b[1A');
// clear the line
process.stdout.write('\u001b[2K');
```

**Comment by doowb** [comment]
Lol... I was spending all this time trying to figure out a way to do that. At least it lead me down the path of fixing the `.cliWidth` method in `readline-utils`.

The `readline-utils` lib has methods for that, you can use it like this:

```js
var utils = require('readline-utils');
var Confirm = require('prompt-confirm');
var confirm = new Confirm('Like chocolate?');

confirm.ask(function(answer) {
  // move up a line
  utils.up(confirm.rl, 1);
  // clear the line
  utils.clearLine(confirm.rl, 1);
  console.log(answer);
});
```

**Comment by jonschlinkert** [comment]
yeah you can use the utils too, but I was just showing a way to do it without a dependency

**Comment by stevenvachon** [comment]
I think the escape codes are clearer. Thank you both!

**Comment by stevenvachon** [comment]
```js
confirm.renderMessage = function() {
  if (this.status === "answered") {
    // Move up a line and clear
    return "\u001b[1A\u001b[2K";
  } else {
    // Omit the prefix and text formatting
    return `${this.message} `;
  }
};
```

The answered state results in showing the answer only.

Instead, I just did this:
```js
confirm.renderMessage = function() {
  // Omit the prefix and text formatting
  return `${this.message} `;
};

const confirmed = await confirm.run();

// Move up a line and clear [the confirmation]
process.stdout.write("\u001b[1A\u001b[2K");
```

**Comment by jonschlinkert** [comment]
is that what you wanted?

**Comment by jonschlinkert** [comment]
> Instead, I just did this:

why not just do

```js
prompt.run()
  .then(function() {
    process.stdout.write("\u001b[1A\u001b[2K");
  });
```

**Comment by stevenvachon** [comment]
That's actually what is happening under the hood :) The only difference is that I'm using `await`.

**Comment by jonschlinkert** [comment]
@stevenvachon can this  be closed?

**Comment by stevenvachon** [comment]
Thank you.
